<a href="https://colab.research.google.com/github/KezhenLi/Homework2/blob/main/homework2.1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import math
import numpy as np
import random as rand

In [88]:
N = 10 #Number of points
M = 100 #Maximum value of x and y
E = 5 #Maximum value of error
array = np.zeros((3,N)) 
for i in range(N):
  array[0][i] = rand.randint(0,M)
  array[1][i] = rand.randint(0,M)
  array[2][i] = rand.randint(-E,E)
print(array)  #Take a set of N (x,y) points, each with associated errors
Sumx2 = 0   
Sumx = 0
Sumy = 0
Sumxy = 0
a = 0
b = 0
S = 0
Sx = 0
Sy = 0
t = 0
Stt = 0
Sa2 = 0
Sb2 = 0
Chi2 = 0
for i in range(N):
 if array[2][i] != 0:
  Sumx2 = Sumx2 + array[0][i]*array[0][i]
  Sumx = Sumx + array[0][i]
  Sumxy = Sumxy + array[0][i]*array[1][i]
  Sumy = Sumy + array[1][i]
  S = S + 1/(array[2][i]*array[2][i])
  Sx = Sx + array[0][i]/(array[2][i]*array[2][i])
  Sy = Sy + array[1][i]/(array[2][i]*array[2][i])
  Stt = Stt + pow((array[0][i] - Sx/S)/(array[2][i]),2)
a = (1/N*Sumxy*Sumx - 1/N*Sumy*Sumx2)/(1/N*Sumx*Sumx - Sumx2) 
b = (1/N*Sumy*Sumx - 1/N*Sumxy)/(1/N*Sumx*Sumx - Sumx2)
Sa2 = 1/S*(1 + Sx*Sx/(S*Stt))
Sb2 = 1/Stt
print(a,b,Sa2,Sb2) #The best fit straight line parameters and errors on parameters
for j in range(N):
  if array[2][j] != 0:
    Chi2 = Chi2 + pow((array[1][j] - a - b*array[0][j])/array[2][j],2)
print(Chi2) #Chi2/ndf



[[ 44.  33.   8.  89.  95.  83.  86.  83.  23.  22.]
 [ 88.  79.  76.  51.  68. 100.  22.   2.  83.  58.]
 [  5.   0.   0.  -3.  -3.   0.   5.  -2.  -5.   3.]]
26.11770329700347 -0.9854817121472864 13.298750901349777 0.0023729357510904464
5555.305481840158
